/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_amefurikozo_jni_Main */

#ifndef _Included_me_amefurikozo_jni_Main
#define _Included_me_amefurikozo_jni_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_amefurikozo_jni_Main
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_amefurikozo_jni_Main_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
